# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=5)),
                ('latitud', models.DecimalField(decimal_places=10, default='0.0000000000', max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=10, default='0.000000000', max_digits=20)),
            ],
        ),
    ]
