# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='latitud',
            field=models.DecimalField(decimal_places=20, default='0.00000000000000000', max_digits=20),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='longitud',
            field=models.DecimalField(decimal_places=20, default='0.0000000000000000', max_digits=20),
        ),
    ]
