# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0006_auto_20160814_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tienda',
            new_name='sucursal',
        ),
    ]
