# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0007_auto_20160814_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iva_producto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_productos', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Rest.sucursal')),
            ],
        ),
    ]
