# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0008_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
