# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0009_sucursal_id_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='nombre',
            new_name='direccion',
        ),
    ]
