# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0012_auto_20160814_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(default='direccion', max_length=10)),
                ('genero', models.CharField(choices=[('f', 'masculino'), ('m', 'femenino')], max_length=10)),
                ('estadoCivil', models.CharField(choices=[('soltero', 'soltero'), ('casado', 'casado'), ('divorciado', 'divorciado'), ('viudo', 'viudo')], max_length=10)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Rest.sucursal')),
            ],
        ),
    ]
