# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0013_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(default='direccion', max_length=50),
        ),
    ]
