# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0014_auto_20160814_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_factura', models.IntegerField()),
                ('fecha_factura', models.DateTimeField(blank=True, null=True)),
                ('id_facturas', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Rest.cliente')),
            ],
        ),
    ]
