# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0015_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='num_factura',
            field=models.CharField(max_length=10),
        ),
    ]
